spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      # Use Long for keys and Avro for values
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        # Schema Registry connection
        schema.registry.url: "http://localhost:8085"
        # Tells Avro to use the generated POJO class instead of GenericRecord
        specific.avro.reader: true