kafka:
  topic:
    user-topic: user-topic
    user-created-topic: user-created-topic
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Stop sending the Java class name in the message header
        spring.json.add.type.headers: false